### ISSUE TITLE
support to run on terminal

### ISSUE THREAD

**Issue by mrmedium** [commacmms/Airport-departure-board#2]
Is it possible to run it on a terminal like i run it and it just displays the flight details in the linux terminal?

**Comment by commacmms** [comment]
Not directly with the code on this repository but you can write a short python script that sends out the API request at given intervals (note the monthly limit, I have some comments about that on my blog post on this project [here](https://supertechman.blogspot.com)) and prints the response to the terminal. You need to process and format the response. All this can definitely be done.
